modLoader="javafml" #mandatory
loaderVersion="[35,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license="MIT"
issueTrackerURL="https://github.com/jingshenSN2/CraftTime/issues" #optional
[[mods]] #mandatory
modId="timecraft" #mandatory
version="0.3.1" #mandatory
displayName="Craft Time" #mandatory
updateJSONURL="https://raw.githubusercontent.com/jingshenSN2/CraftTime/1.16-forge/update.json" #optional
displayURL="https://www.curseforge.com/minecraft/mc-mods/craft-time" #optional
logoFile="icon.png" #optional
credits="" #optional
authors="SN2" #optional
description=''' Time to craft!
'''
[[dependencies.timecraft]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[35,)" #mandatory
    ordering="NONE"
    side="BOTH"
[[dependencies.timecraft]]
    modId="minecraft"
    mandatory=true
   versionRange="[1.16.4,1.17)"
    ordering="NONE"
    side="BOTH"
